### ISSUE TITLE
Look into semantic-release/git

### ISSUE THREAD

**Issue by ice-breaker-tg** [web3-storage/w3up-client#19]
This is a separate plugin that will auto-commit changes made during release (including updating package.json version).
This should also run the npm build script to build types and auto update the API.md
The types should be moved to dist.

sibling task to https://github.com/web3-storage/w3up-cli/issues/86

**Comment by alanshaw** [comment]
Most other web3.storage and nft.storage repos use [release please](https://github.com/googleapis/release-please#readme) to manage automated release and publish flow. A minimal version of this can be seen [here in w3ui](https://github.com/web3-storage/w3ui/blob/main/.github/workflows/release.yml). It would be rad to keep consistency 😇.

**Comment by alanshaw** [comment]
Added release please in https://github.com/web3-storage/w3up-client/commit/7bd91d59da2b961a4227d9c062e74169e645a0bc
