### ISSUE TITLE
Look into rollup/ipjs/etc for building different dist versions.

### ISSUE THREAD

**Issue by ice-breaker-tg** [web3-storage/w3up-client#20]
This should probably happen after #19 
Should build commonjs,esm,etc into a dist folder.
Update package.json files option to point to correct output.

needs #19

**Comment by alanshaw** [comment]
We use rollup to build the current web3.storage and nft.storage clients e.g. https://github.com/web3-storage/web3.storage/tree/main/packages/client - you can probably steal most of that.

**Comment by gobengo** [comment]
after https://github.com/web3-storage/w3protocol/pull/653 , releases happen from another repo
