### ISSUE TITLE
doc: content CID vs CAR CID

### ISSUE THREAD

**Issue by mikeal** [web3-storage/w3up-client#23]
the docs and API work with both content CIDs and CAR CIDs but we aren’t explicit right now about which one we’re talking about.

the technology here is somewhat confusing, so we should find the best way to unify when/where we expose each kind of CID and make sure we come up with consistent language for the docs that can differentiate them.

**Comment by alanshaw** [comment]
So, we should probably not refer as "content CIDs" - reads as "content content identifiers".

I've considered "DAG CID" but probably too ambiguous. IDK "Data CID"? We have prior art of using it to refer to the CID of the data that dagcargo aggregates and stores in the filecoin deal e.g. https://api.web3.storage/status/bafybeidf7igbd7pu46s6obhzvzpmjsoogn2gaqxgeuh2wlxbmrosvndcv4 (`deals[0].dataCid`).

**Comment by jchris** [comment]
I independently came up with `dagCID` in #239 -- I think an important point about them is that there can be more than one per upload, and more than one per CAR file, even though usually there is only one.

**Comment by jchris** [comment]
Or maybe we just say `CID` and `CAR CID`

**Comment by ice-breaker-tg** [comment]
Consolidated into #41
