### ISSUE TITLE
we should call `remove` unlink at the code level

### ISSUE THREAD

**Issue by jchris** [web3-storage/w3up-client#3]
Let's rename remove to unlink everywhere.

https://github.com/web3-storage/w3up-client/blob/aea33196040dd2d8df0fda5d42194e68d408d8c0/src/store/store/capability.js#L32

**Comment by JeffLowe** [comment]
Capabilities are cross-stack concerns, and originate in https://github.com/web3-storage/ucan-protocol/blob/master/packages/access/src/capabilities.js
Changing in only one place risks breaking commands. This likely needs to be ticketed for @hugomrdias consideration...then whatever is decided we can mirror in the client.

**Comment by hugomrdias** [comment]
add this to my board do we have a priority for this ?

**Comment by alanshaw** [comment]
@jchris can we get a reason for this request? We now also have `upload/remove` and so it has become convention. I think "add" goes with "remove" not "unlink". If we _really_ want it we should consider changing "add" to "link" also.

I'm going to close as wontfix but please reopen with reasoning if you really want to persue 🙂
