### ISSUE TITLE
docs: Output of `client.lists` is not iterable

### ISSUE THREAD

**Issue by joshJarr** [web3-storage/w3up-client#31]
Hi,

Looks like this code for listing CIDs [outlined in the readme](https://github.com/web3-storage/w3up-client#listing-uploads) is incorrect.
```
async function listUploads() {
  // CLIENT_OPTS should be defined as described in "Creating a client object"
  const client = createClient(CLIENT_OPTS)
  const cids = await client.list()
  for (const cid of cids) {
    console.log('CID:', cid)
  }
```

When listing CIDs this way I get `TypeError: cids is not iterable`. Looks like this should perhaps be `cids.results`?

**Comment by ice-breaker-tg** [comment]
consolidated into #41
