### ISSUE TITLE
`TypeError: this.spaces.set is not a function`

### ISSUE THREAD

**Issue by adamazad** [web3-storage/w3up-client#71]
Hi, we're implementing the client in our project like below

```typescript

export const W3UP_SPACE_NAME = 'assets.nimi.page';
export const W3UP_CLIENT_EMAIL = 'adam@nimi.io';

export async function prepareW3UpClient() {
  const client = await create();
  const space = await client.createSpace(W3UP_SPACE_NAME);
 
  try {
    await client.setCurrentSpace(space.did());
    await client.registerSpace(W3UP_CLIENT_EMAIL);
  } catch (err) {
    console.error('registration failed: ', err);
  }

  return client;
}
```

But I get:

```
registration failed:  TypeError: this.spaces.set is not a function
    at AgentData.addSpace (file:///Users/adam/workspace/nimi/nimi-services/node_modules/@web3-storage/access/src/agent-data.js:120:17)
    at Agent.createSpace (file:///Users/adam/workspace/nimi/nimi-services/node_modules/@web3-storage/access/src/agent.js:265:22)
    at async Client.createSpace (file:///Users/adam/workspace/nimi/nimi-services/node_modules/@web3-storage/w3up-client/src/client.js:89:27)
    at async prepareW3UpClient (file:///Users/adam/workspace/nimi/nimi-services/src/modules/ipfs/index.ts:21:19)
    at async startService (file:///Users/adam/workspace/nimi/nimi-services/src/index.ts:20:3)
```

**Comment by vasco-santos** [comment]
Hey @adamazad 
Might be a versions mismatch. Can you let us know versions you are using?

**Comment by vasco-santos** [comment]
I have this example running in Node.js with all latest deps https://github.com/vasco-santos/w3up-tester/blob/main/index.js#L33-L63 in case it helps

**Comment by adamazad** [comment]
Hi @vasco-santos, I still get the same error. Full content:

```typescript
import { randomBytes } from 'crypto';

import { create as createClient } from '@web3-storage/w3up-client';

type Client = Awaited<ReturnType<typeof createClient>>;

export const W3UP_SPACE_NAME = 'assets.nimi.page';
export const W3UP_CLIENT_EMAIL = 'adam@nimi.io';

async function main() {
  const client = await createClient({});

  await register(client);

  const bytes = await randomBytes(128);
  const file = new Blob([bytes]);

  try {
    const successMessage = await client.uploadFile(file);
    console.log(successMessage);
  } catch (err) {
    console.log('err', err);
  }
}

main();

async function register(client: Client) {
  const space = await client.createSpace('my-awesome-space');
  await client.setCurrentSpace(space.did());
  await client.registerSpace(W3UP_CLIENT_EMAIL);
}
```


Error:

```
file:///Users/adam/workspace/nimi/nimi-services/node_modules/@web3-storage/access/src/agent-data.js:115
    this.spaces.set(did, meta)
                ^
TypeError: this.spaces.set is not a function
    at AgentData.addSpace (file:///Users/adam/workspace/nimi/nimi-services/node_modules/@web3-storage/access/src/agent-data.js:115:17)
    at Agent.createSpace (file:///Users/adam/workspace/nimi/nimi-services/node_modules/@web3-storage/access/src/agent.js:263:22)
    at async Client.createSpace (file:///Users/adam/workspace/nimi/nimi-services/node_modules/@web3-storage/w3up-client/src/client.js:89:27)
    at async register (file:///Users/adam/workspace/nimi/nimi-services/src/modules/ipfs/index.ts:29:17)
    at async main (file:///Users/adam/workspace/nimi/nimi-services/src/modules/ipfs/index.ts:13:3)
```

Node v18.12.1 if that helps

**Comment by vasco-santos** [comment]
@adamazad same Node version here. I was meaning version of client. Can you reinstall all dependencies?

```
➜  w3up-tester git:(main) npm ls @web3-storage/w3up-client
w3up-tester@1.0.0 /Users/vcs/git/web3-storage/w3up-tester
└── @web3-storage/w3up-client@4.0.1

➜  w3up-tester git:(main) npm ls @web3-storage/access
w3up-tester@1.0.0 /Users/vcs/git/web3-storage/w3up-tester
└─┬ @web3-storage/w3up-client@4.0.1
  └── @web3-storage/access@9.2.0
```

It looks like it might exist a dependency with older version.

**Comment by adamazad** [comment]
@vasco-santos, looks about right:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/1926216/208520007-66a00176-ad0a-4c34-9d7c-ae539454d6ba.png">

**Comment by vasco-santos** [comment]
@adamazad sad you are going through this issue. I have not been able to replicate, just tried today also using Typescript and also works fine for me: https://github.com/vasco-santos/w3up-tester/blob/chore/use-tsc/x.ts

Can you run my example with this branch and let me know if it works for you?

```sh
npm i
npm run build
node dist/x.js
```

It might be something related to the compilation to typescript. If you can get me a repo to test would also be helpful for debugging

**Comment by adamazad** [comment]
Same error 😅 

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/1926216/208637289-7c98eed9-c6f8-4648-a100-be4fa9f14121.png">


ts output:


```javascript
import { randomBytes } from 'crypto';
import { create as createClient } from '@web3-storage/w3up-client';
export const W3UP_SPACE_NAME = 'assets.nimi.page';
export const W3UP_CLIENT_EMAIL = 'vasko_10@hotmail.com';
async function main() {
    const client = await createClient({});
    await register(client);
    const bytes = await randomBytes(128);
    const file = new Blob([bytes]);
    try {
        const successMessage = await client.uploadFile(file);
        console.log(successMessage);
    }
    catch (err) {
        console.log('err', err);
    }
}
main();
async function register(client) {
    const space = await client.createSpace('my-awesome-space');
    await client.setCurrentSpace(space.did());
    await client.registerSpace(W3UP_CLIENT_EMAIL);
}
//# sourceMappingURL=x.js.map
```

**Comment by vasco-santos** [comment]
I dived a bit deeper and I think something is wrong with your local config store. Did you try this before and was working? I would suspect an update is causing issues.

If you do not have anything important there, I recommend that you try:
- go to your `node_modules/@web3-storage/w3up-client/src/index.node.js` and comment lines https://github.com/web3-storage/w3up-client/blob/main/src/index.node.js#L26-L27 - this will force a creation of a new local store.

Alternatively, we need to see what is on your conf file. My conf file on OSX is located in `/Users/$USER_NAME/Library/Preferences/w3access/w3up-client.json`. Checking this JSON I have a `"spaces":{"$map":[` which looks like what your conf file does not have

**Comment by adamazad** [comment]
> Did you try this before and was working? I would suspect an update is causing issues.

Yes, it worked once (I got the email and verified it).

> Alternatively, we need to see what is on your conf file. My conf file on OSX is located in /Users/$USER_NAME/Library/Preferences/w3access/w3up-client.json. Checking this JSON I have a "spaces":{"$map":[ which looks like what your conf file does not have

Isn't there a way to change the path? I may want to use different configuration per node project.

**Comment by vasco-santos** [comment]
@adamazad yes, I was now looking into this:

https://github.com/web3-storage/w3up-client#clientfactoryoptions

It is possible to bring your own config and therefore specifying your own name. 

A non tested code that should make it work:
```js
import { StoreConf } from '@web3-storage/access/stores/store-conf'
import { create as createClient } from '@web3-storage/w3up-client'

const store = new StoreConf({ profile: 'custom-client' })
const client = await createClient({
  store
})
```

**Comment by adamazad** [comment]
Hi, @vasco-santos above worked for once and managed to upload a random byte to the network. 
Now running into the same problem of `TypeError: this.spaces.set is not a function`. 

Now to the real-world use case, this flow is not ideal in a server setup.

- Do I have to manually validate the login every time I initiate a client and DID? 
- We use a container to run our API instances, does this mean restarting the container for upgrades and results in this fatal error?

**Comment by vasco-santos** [comment]
Hi @adamazad 

Having that error again seems weird and unexpected. I can't replicate on my end. Given I am not familiar with that part of the codebase I might be missing some edge case thing. Perhaps @hugomrdias can help us here?

> Do I have to manually validate the login every time I initiate a client and DID?

No, this is only needed in the first time. The config file is then set with all the proofs you need to not register again. You will need when new spaces are created.

**Comment by alanshaw** [comment]
@adamazad are you still getting `TypeError: this.spaces.set is not a function`?

For use on the server, you could create a private key for the server to use, and delegate permissions to the server to upload to a pre-registered space. That way the server can use the private key and permission by loading them via env variables each time it is restarted.

Something like this right now https://gist.github.com/alanshaw/e949abfcf6728f590ac9fa083dba5648

I haven't tested yet so might be bugs. I'd also like this make this less complicated...

**Comment by vasco-santos** [comment]
@adamazad can confirm this works

**Comment by alanshaw** [comment]
@vasco-santos says he used the gist and it worked!

**Comment by alanshaw** [comment]
@adamazad did this work for you?
